# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86ecfad2742fd0c9f98f02d9c56658319a11314ec9c0582fc86a01d319becf5542b4e295de039d65c479ace0c84258f819a0743af838f91d8595ccc631c362e7

test:
  secret_key_base: 114de2a3b0474fa5c69a4a8ad6f2ea8a0de2fdf3aea174bbfb8891f981de6c87deab96cb72554ad5e12b948616044ac6af29456a08dbbe0acdc691420cc271c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
